# config.yaml
name_project: empty_project
type_project: executable
description: Empty project in Next
version: v0.0.1
build_dir: build

# config.yaml
commands:
  build: g++ src/main.cpp -o build/app
  clean: rm -r build/app
  run: ./build/app
